global:
  namespace: monitoring
  dockeruser: minhhuy27

services:
  api-gateway:
    name: api-gateway
    image:
      tag: loki-test-v1

  config-server:
    name: config-server
    image:
      tag: loki-test-v1

  discovery-server:
    name: discovery-server 
    image:
      tag: loki-test-v1 

  customers-service:
    name: customers-service
    image:
      tag: loki-test-v1

  visits-service:
    name: visits-service
    image:
      tag: loki-test-v1

  vets-service:
    name: vets-service
    image:
      tag: loki-test-v1